---
title: "pollution_map"
output: html_document
---

Next Steps: 
1. Finish fixing inconsistencies - i think all the major / noticable ones are fixed
2. decide if we like aesthetics 
3. animate / figure out how to link to shiny selectors [at Wed meeting]

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(here)
library(janitor)
# install.packages("leaflet") # Source: https://rstudio.github.io/leaflet/
# library(leaflet)
library(maps)
library(scales)
```

## Load Data 

```{r load-data, message = FALSE}
# air pollution data
death_rates_from_air_pollution_csv <- read_csv(
  here("data", "death-rates-from-air-pollution.csv"), show_col_types = FALSE)

number_deaths_by_risk_factor_csv <- read_csv(
  here("data", "number-of-deaths-by-risk-factor.csv"), show_col_types = FALSE)

# gdp data
gdp_by_country_csv <- read_csv(
  here("data", "gdp-data.csv"), show_col_types = FALSE)

# NOTE: added _csv ending to eliminate need for naming later versions "clean"

# world map data
world_map_data <- map_data("world") %>% 
  as_tibble()
```

## Clean Data 

```{r clean-datasets}

#renaming variables to clean them up 

death_rates_from_air_pollution <- death_rates_from_air_pollution_csv %>%
  clean_names() %>%
  rename(
    death_rate_air_pollution =
      deaths_air_pollution_sex_both_age_age_standardized_rate,
    death_rate_household_pollution = deaths_household_air_pollution_from_solid_fuels_sex_both_age_age_standardized_rate,
    death_rate_ambient_matter_pollution = deaths_ambient_particulate_matter_pollution_sex_both_age_age_standardized_rate,
    death_rate_ozone_pollution =
      deaths_ambient_ozone_pollution_sex_both_age_age_standardized_rate
  )

number_deaths_by_risk_factor <- number_deaths_by_risk_factor_csv %>%
  clean_names()

gdp_by_country <- gdp_by_country_csv %>%
  clean_names() %>%
  pivot_wider()
```

## Data Wrangling 

```{r data wrangling}
# joining air pollution data together
air_pollution_joined <- death_rates_from_air_pollution %>% 
  left_join(number_deaths_by_risk_factor, by = c("entity", "year", "code"))

# Next Step: Do a series of case_when (before join) to resolve inconsistencies 
  # noticeable ones include: French Guiana (but there might just not be data on this)

# clean world_map_data 
world_map_data <- world_map_data %>% 
  mutate(region = case_when(
    region == "Ivory Coast" ~ "Cote d'Ivoire", 
    TRUE ~ region
  ))

# clean air pollution data

air_pollution_joined <- air_pollution_joined %>% 
  mutate(entity = case_when(
    entity == "United States" ~ "USA", 
    entity == "United Kingdom" ~ "UK",
    entity == "Czechia" ~ "Czech Republic",
    entity == "Congo" ~ "Republic of Congo",
    entity == "Democratic Republic of Congo" ~ "Democratic Republic of the Congo",
    TRUE ~ entity
  ))


# joining air pollution to world_map_data
total_joined <- world_map_data %>% 
  left_join(air_pollution_joined, by = c("region" = "entity"))

to_do <- world_map_data %>% 
  anti_join(air_pollution_joined, by = c("region" = "entity"))
  
to_do %>% 
  pull(region) %>% 
  unique()

```

## Type of Pollution Map 

```{r test map, out.width="100%"}
ggplot(total_joined, aes(long, lat)) + 
  geom_polygon(aes(group = group, fill = death_rate_air_pollution), 
               color = "black", size = 0.3) + 
  coord_map(projection = "mercator", 
            xlim = c(-180, 180)) + 
  scale_fill_viridis_c(option = "turbo", 
                       # turbo pallet coordinates with AQI colors (https://webcam.srs.fs.fed.us/test/AQI.shtml)
    name = "Total death rate",
    labels = label_number(big.mark = ","),
    na.value = "lightgray" 
  ) +
  theme_void() +  
  theme(
    text = element_text(color = "black"),
    legend.position = "bottom",
    legend.key.width = unit(2, "cm"),
    legend.key.height = unit(0.3, "cm"),
    plot.background = element_rect(fill = "white", color = "white"),
    plot.title = element_text(hjust = 0.5),
    plot.subtitle = element_text(hjust = 0.5)
  ) +
  labs(
    title = "Total Death Rate from Air Pollution",
    subtitle = "By country, from 1970 to 2017",
    caption = "Source: Our World in Data"
  )

```

## Risk Factors Map 

## Risk Factors Line Chart 

```{r filter for regions and SDI}
regions <- air_pollution_joined %>% 
  filter(entity == "Central Asia" | 
           entity == "Central Europe" | 
           entity == "Central Europe, Eastern Europe, and Central Asia" | 
           entity == "Central Latin America"| 
           entity == "Central Sub-Saharan Africa" | 
           entity == "East Asia "| 
           entity == "Eastern Europe"| 
           entity == "Eastern Sub-Saharan Africa"| 
           entity == "Latin America and Caribbean"| 
           entity == "North Africa and Middle East"| 
           entity == "North America"| 
           entity == "South Asia"| 
           entity == "Southeast Asia"| 
           entity == "Southeast Asia, East Asia, and Oceania"| 
           entity == "Southern Latin America"| 
           entity == "Southern Sub-Saharan Africa"| 
           entity == "Sub-Saharan Africa"| 
           entity == "Tropical Latin America"| 
           entity == "Western Europe"| 
           entity == "Western Sub-Saharan Africa") 

regions_limited <- air_pollution_joined %>% 
  filter(entity == "Central Asia" | 
           entity == "Central Europe" | 
           entity == "Central Latin America"| 
           entity == "Central Sub-Saharan Africa" | 
           entity == "East Asia "| 
           entity == "Eastern Europe"| 
           entity == "Eastern Sub-Saharan Africa"| 
           entity == "Latin America and Caribbean"| 
           entity == "North Africa and Middle East"| 
           entity == "North America"| 
           entity == "South Asia"| 
           entity == "Southeast Asia"| 
           entity == "Southern Latin America"| 
           entity == "Southern Sub-Saharan Africa"| 
           entity == "Sub-Saharan Africa"| 
           entity == "Tropical Latin America"| 
           entity == "Western Europe"| 
           entity == "Western Sub-Saharan Africa") 


sdi <- air_pollution_joined %>% 
  filter(entity ==  "High SDI" | 
        entity == "High-middle SDI" | 
        entity == "Low SDI" | 
        entity == "Low-middle SDI" |
        entity == "Middle SDI") 
    
```



```{r regions and SDI plot}

#figure out how to have user input change y axis 

# copy code to allow user to select entity plotted 

ggplot(data = regions_limited, aes(x = year, y = unsafe_water_source)) + 
  geom_line(aes(group = entity, color = entity)) + 
  theme(legend.position = "bottom") + 
  labs(
        x = "Year",
        y = "Unsafe Water Source",
        color = "Region",
        title = "Risk Factor")


ggplot(data = sdi, aes(x = year, y = unsafe_water_source)) + 
  geom_line(aes(group = entity, color = entity))

```


