---
title: "Air Pollution Deaths"
subtitle: "Presentation subtitle: SOMETHING ABOUT SHINY APP/ 1 SENTENCE SUMMARY"
author: "Tidy Team  <br> Drew Flanagan, Courtney Lee, Kathryn Thomas, Raghav Rasal"
institute: "Duke University"
date: "`r Sys.Date()`"
output:
  xaringan::moon_reader:
    css: xaringan-themer.css
    lib_dir: libs
    nature:
      ratio: "16:9"
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
---

```{r load-packages, include = FALSE}
# Add any additional packages you need to this chunk
# Remove any packages from this list that you're not using
library(tidyverse)
library(knitr)
library(xaringanthemer)
```

```{r setup, include=FALSE}
# For better figure resolution
knitr::opts_chunk$set(
  fig.retina = 3, 
  dpi = 300, 
  fig.width = 6, 
  fig.asp = 0.618, 
  out.width = "70%"
  )
```

```{r load-data, include=FALSE}
# Load your data here
```

```{r style-slides, echo = FALSE}
style_xaringan(
  title_slide_background_image = "img/watercolour_sys02_img34_teacup-ocean.jpg"
)
```

class: inverse, middle, center

# Motivation

---

## Inspiration + Data

- text, text, text

- Use `---` to separate slides and `--` for incremental builds

--

- Like this

---

## Workflow

You can use plain text

- or bullet points

.pull-left[
or text in two columns $^*$
]
.pull-right[
- like
- this
]

.footnote[
[*] And add footnotes
]

---

class: inverse, middle, center

# The Shiny App

### try to hyperlink this directly to the shiny app

